export const CONFIG = {
  FORM_SHEET: 'Form Responses 1',
  APPROVED_SHEET: 'Approved-Requests',
  MEDDB_SHEET: 'MEDDB3',
  PROCESS_FROM_DATE: '2026-07-01',
  FUZZY_THRESHOLD: 0.55,
  LOW_MATCH_THRESHOLD: 0.72,
  DEFAULT_QTY: 1,
  MAX_MEDS: 7,
} as const;

// 1-based column indexes - Form Responses 1
export const FR = {
  EMAIL: 3,
  PREFIX: 4,
  EMP_ID: 5,
  EMP_NAME: 6,
  TIMESTAMP: 7,
  JOB: 8,
  COMPANY: 9,
  DEPT: 10,
  PATIENT: 11,
  PHONE: 12,
  CARD_PHOTO: 13,
  PROOF_RELATION: 16,
  ROSHETTA: 19,
  MED_START: 20,
  MED_END: 26,
  LABS_1: 27,
  LABS_2: 28,
  RELATION: 34,
  REJECTION_EMAIL: 35,
  NATIONAL_ID: 36,
  COMMENTS: 37,
} as const;

// 1-based column indexes - Approved-Requests
export const AR = {
  COMPANY: 1,
  EMP_NAME: 2,
  ID: 3,
  PHONE: 4,
  LAST_UPDATE: 5,
  PATIENT: 6,
  OL: 7,
  REQUESTED_MED: 8,
  QTY: 9,
  PRICE_TOTAL: 10,
  FROM: 11,
  LAST_GIVEN_TO: 12,
  TO: 13,
  BLANK1: 14,
  COMPANY_DRUG: 15,
  ALT1: 16,
  ALT2: 17,
  NEW_MED: 18,
  QTY2: 19,
  BLANK2: 20,
  NOTES: 21,
} as const;
